spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

resilience4j:
  retry:
    instances:
      retry_notifications: #OK
        max-attempts: 3
        wait-duration: 5s
        retry-exceptions:
          - org.springframework.dao.DataAccessException
          - org.springframework.dao.DataAccessResourceFailureException

      retry_occult_notifications: #OK
        max-attempts: 3
        wait-duration: 5s
        retry-exceptions:
          - org.springframework.dao.DataAccessException
          - org.springframework.dao.DataAccessResourceFailureException

      retry_visualisation: #OK
        max-attempts: 3
        wait-duration: 5s
        retry-exceptions:
          - org.springframework.dao.DataAccessException
          - org.springframework.dao.DataAccessResourceFailureException

      retry_occult:
        max-attempts: 3
        wait-duration: 5s
        retry-exceptions:
          - org.springframework.dao.DataAccessException
          - org.springframework.dao.DataAccessResourceFailureException
        ignore-exceptions:
          - br.com.device_notification.infra.exceptions.NotificationNotFound

      retry_count: #OK
        max-attempts: 3
        wait-duration: 5s
        retry-exceptions:
          - org.springframework.dao.DataAccessException
          - org.springframework.dao.DataAccessResourceFailureException

  circuitbreaker:
    instances:
      circuitbreaker_notifications: #Ok
        sliding-window-size: 5
        minimum-number-of-calls: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - org.springframework.dao.DataAccessException
          - org.springframework.dao.DataAccessResourceFailureException

      circuitbreaker_occult_notifications: #OK
        sliding-window-size: 5
        minimum-number-of-calls: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - org.springframework.dao.DataAccessException
          - org.springframework.dao.DataAccessResourceFailureException

      circuitbreaker_visualisation: #OK
        sliding-window-size: 5
        minimum-number-of-calls: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - org.springframework.dao.DataAccessException
          - org.springframework.dao.DataAccessResourceFailureException
        ignore-exceptions:
          - br.com.device_notification.infra.exceptions.ServiceUnavailable

      circuitbreaker_occult: #OK
        sliding-window-size: 5
        minimum-number-of-calls: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - org.springframework.dao.DataAccessException
          - org.springframework.dao.DataAccessResourceFailureException
        ignore-exceptions:
          - br.com.device_notification.infra.exceptions.NotificationNotFound
          - br.com.device_notification.infra.exceptions.ServiceUnavailable

      circuitbreaker_count: #OK
        sliding-window-size: 5
        minimum-number-of-calls: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - org.springframework.dao.DataAccessException
          - org.springframework.dao.DataAccessResourceFailureException
        ignore-exceptions:
          - br.com.device_notification.infra.exceptions.ServiceUnavailable